#!/bin/python

import math
import os
import random
import re
import sys
from collections import deque

# Complete the rotLeft function below.
def rotLeft(a, d):
    b = deque(a)
    for i in range(d):
        t = b.popleft()
        b.append(t)
    return(list(b))
        
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nd = raw_input().split()

    n = int(nd[0])

    d = int(nd[1])

    a = map(int, raw_input().rstrip().split())

    result = rotLeft(a, d)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
