#!/bin/python

import math
import os
import random
import re
import sys

# Complete the minimumSwaps function below.
def minimumSwaps(arr): 
    count=0
    j=0
    while j<len(arr):
        if j==6 and len(arr)==7:
            break
        if arr[j]==(j+1):
            j+=1
            continue
        arr[arr[j]-1], arr[j] = arr[j], arr[arr[j]-1]
        count+=1
    return count

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(raw_input())

    arr = map(int, raw_input().rstrip().split())

    res = minimumSwaps(arr)

    fptr.write(str(res) + '\n')

    fptr.close()
